scopes:
    log:
        label: luketowers.easyaudit::lang.models.activity.log
        type: group
        scope: inLog
        modelClass: LukeTowers\EasyAudit\Models\Activity
        options: getLogOptions
    event:
        label: luketowers.easyaudit::lang.models.activity.event
        type: group
        scope: withEvent
        modelClass: LukeTowers\EasyAudit\Models\Activity
        options: getEventOptions
    source:
        label: luketowers.easyaudit::lang.models.activity.source
        type: group
        scope: fromSources
        modelClass: LukeTowers\EasyAudit\Models\Activity
        options: getSourceOptions
    subject_type:
        label: luketowers.easyaudit::lang.models.activity.subject
        type: group
        scope: toSubjectTypes
        modelClass: LukeTowers\EasyAudit\Models\Activity
        options: getSubjectTypeOptions
    created_at:
        label: luketowers.easyaudit::lang.controllers.activities.filters.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'
